steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'chmod +x ./gradlew'
      -
  # Build the application image using Buildpacks
  - name: 'gradle'
    entrypoint: 'gradle'
    args: ['build', '--no-daemon']

  - name: 'gcr.io/k8s-skaffold/pack'
    args: ['build', '${_IMAGE_NAME}', '--builder=gcr.io/buildpacks/builder:v1', '--path=.', '--env=GOOGLE_RUNTIME_VERSION=17' ]

  # Push the built image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
