logging:
  level:
    org:
      springframework:
        security: ERROR
spring:
  server:
    port: 8080
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: redacted
            clientSecret: redacted
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"


  data:
    mongodb:
      uri: redacted
      database: test

ocr:
  url: ocr.ishananand.ca

